import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

public class AddAttendance extends javax.swing.JFrame {

    /**
     * Creates new form teacher_home
     */
    public AddAttendance() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(650, 620));
        setMinimumSize(new java.awt.Dimension(650, 620));
        setPreferredSize(new java.awt.Dimension(650, 620));
        setResizable(false);
        setSize(new java.awt.Dimension(650, 620));

        jPanel1.setMaximumSize(new java.awt.Dimension(650, 620));
        jPanel1.setMinimumSize(new java.awt.Dimension(650, 620));
        jPanel1.setPreferredSize(new java.awt.Dimension(650, 620));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ADD ATTENDANCE");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 10, 650, 49);

        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton2.setText("BACK");
        jButton2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(562, 556, 78, 33);

        jButton3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton3.setText("ADD ABSENTEES");
        jButton3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton3.setMaximumSize(new java.awt.Dimension(203, 31));
        jButton3.setMinimumSize(new java.awt.Dimension(203, 31));
        jButton3.setName(""); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(136, 160, 400, 33);

        jButton4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton4.setText("ADD MEDICAL LEAVE / ON DUTY");
        jButton4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(136, 268, 400, 33);

        jButton5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton5.setText("OK");
        jButton5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(287, 556, 75, 33);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vertical Background.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 650, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here ADD ABSENTEES
        dispose();
        AddAbsentees addAbsentees=new AddAbsentees();
        addAbsentees.setVisible(true);
    }

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here  MEDICAL / OD
        dispose();
        AddExcemption addExcemption = new AddExcemption();
        addExcemption.setVisible(true);
    }

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here OK
        try
        {

            {
                System.out.println("begenning");
                Class.forName("oracle.jdbc.driver.OracleDriver");
                Connection conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521/xe", Login.orclusername, "Kirthic2002");//your username and password
                String sql = "select courseid from faculty where username='"+Login.username+"'";
                System.out.println(Login.username);
                System.out.println(sql);
                PreparedStatement ps = conn.prepareStatement(sql);
                ResultSet rs = ps.executeQuery();
                System.out.println("hellp");
                if(rs.next())
                {
                    System.out.println("nameste");
                    String sql1="update attendance set total_classes=total_classes+1 , no_of_attended_classes=no_of_attended_classes+1 where courseid='"+rs.getString("courseid")+"'";
                    PreparedStatement ps1= conn.prepareStatement(sql1);
                    ResultSet rs1 = ps1.executeQuery();
                    rs1.next();
                    String sql2="update attendance set attendance_percent=(100*no_of_attended_classes)/total_classes , attendance_percent_with_excemption = (100*(no_of_attended_classes+excempted_classes))/total_classes where courseid = '"+rs.getString("courseid")+"'";
                    PreparedStatement ps2= conn.prepareStatement(sql2);
                    ResultSet rs2 = ps2.executeQuery();
                    rs2.next();
                }
                dispose();
                TeacherHome teacherHome=new TeacherHome();
                teacherHome.setVisible(true);

            }
        }
        catch (Exception e)
        {
            System.out.println(e);
        }
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here BACK
    }

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration
}