import net.proteanit.sql.DbUtils;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

public class AddExcemption extends javax.swing.JFrame {

    /**
     * Creates new form teacher_medleave
     */
    public String uname;
    public AddExcemption() {
        initComponents();
        try
        {


            {
                Class.forName("oracle.jdbc.driver.OracleDriver");
                Connection conn= DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521/xe",Login.orclusername,"Kirthic2002");//your username and password
                String sql="select name , rollno ,department,section  from student" ;
                PreparedStatement ps=conn.prepareStatement(sql);
                ResultSet rs=ps.executeQuery();
                jTable1.setModel(DbUtils.resultSetToTableModel(rs));

            }
        }
        catch (Exception e)
        {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1152, 740));
        setMinimumSize(new java.awt.Dimension(1152, 740));
        setPreferredSize(new java.awt.Dimension(1152, 740));

        jPanel1.setMaximumSize(new java.awt.Dimension(1152, 720));
        jPanel1.setMinimumSize(new java.awt.Dimension(1152, 720));
        jPanel1.setPreferredSize(new java.awt.Dimension(1152, 720));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("MEDICAL LEAVE / ON DUTY");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(340, 10, 510, 43);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setText("ROLL NUMBER");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 100, 180, 29);

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jPanel1.add(jTextField1);
        jTextField1.setBounds(30, 150, 300, 28);

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton1.setText("OK");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(980, 650, 73, 33);

        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton2.setText("BACK");
        jButton2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(30, 650, 71, 33);


        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(370, 100, 680, 490);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BACKGROUND.jpg"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 0, 1160, 720);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here BACK:
        dispose();
        AddAttendance addAttendance = new AddAttendance();
        addAttendance.setVisible(true);
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here OK:
        try
        {

            {
                System.out.println("begenning");
                Class.forName("oracle.jdbc.driver.OracleDriver");
                Connection conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521/xe", Login.orclusername, "Kirthic2002");//your username and password
                String sql = "select courseid from faculty where username='"+Login.username+"'";
                System.out.println(Login.username);
                System.out.println(sql);
                PreparedStatement ps = conn.prepareStatement(sql);
                ResultSet rs = ps.executeQuery();
                System.out.println("hellp");
                if(rs.next())
                {
                    System.out.println("nameste");
                    String sql1="update attendance set  no_of_attended_classes=no_of_attended_classes-1 ,excempted_classes=excempted_classes+1 where courseid='"+rs.getString("courseid")+"' and rollno='"+jTextField1.getText()+"'";
                    PreparedStatement ps1= conn.prepareStatement(sql1);
                    ResultSet rs1 = ps1.executeQuery();
                    rs1.next();
                }
                dispose();
                AddAttendance addAttendance = new AddAttendance();
                addAttendance.setVisible(true);

            }
        }
        catch (Exception e)
        {
            System.out.println(e);
        }
    }


    // Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration
}