import javax.swing.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

public class EditStudent extends javax.swing.JFrame {

    /**
     * Creates new form EditStudent
     */
    public final String rno;
    public final String uname;
    public EditStudent(String rollno) {
        initComponents();
        rno=rollno;
        try {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521/xe", Login.orclusername, "Kirthic2002");

            String sql = "select * from student where rollno = '" + rollno + "'";

            PreparedStatement ps = conn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            if(rs.next()) {
                jTextField1.setText(rs.getString("name"));
                jTextField2.setText(rs.getString("rollno"));
                jTextField3.setText(rs.getString("department"));
                jTextField4.setText(rs.getString("section"));
                jPasswordField1.setText(rs.getString("password"));

                ps.close();
                rs.close();
            }
        }
        catch(Exception e)
        {
            System.out.println(e.getStackTrace());
        }
        uname=jTextField2.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(650, 600));
        setMinimumSize(new java.awt.Dimension(650, 600));
        setPreferredSize(new java.awt.Dimension(650, 600));
        setResizable(false);

        jPanel1.setMaximumSize(new java.awt.Dimension(650, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(650, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(650, 600));
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel3.setText("EDIT STUDENT");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(180, 11, 267, 43);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel4.setText("NAME");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 100, 100, 29);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(30, 150, 250, 27);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel9.setText("ROLL NO/USERNAME");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(340, 100, 360, 29);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2);
        jTextField2.setBounds(340, 150, 250, 27);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel5.setText("DEPARTMENT");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 200, 180, 29);

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField3);
        jTextField3.setBounds(30, 250, 250, 27);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel6.setText("SECTION");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(340, 200, 120, 29);

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField4);
        jTextField4.setBounds(340, 250, 250, 27);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel8.setText("PASSWORD");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(30, 300, 190, 29);

        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jPasswordField1);
        jPasswordField1.setBounds(30, 350, 250, 27);

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton1.setText("EDIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(250, 525, 116, 33);

        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(500, 525, 97, 37);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VERTICAL BACKGROUND.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 650, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here NAME:
    }

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here ROLLNO:
    }

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here DEPARTMENT:
    }

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here SECTION:
    }

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here PASSWORD:
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here EDIT:
        try {
            if (jTextField1.getText().length() == 0 || jTextField2.getText().length() == 0 || jTextField3.getText().length() == 0 || jTextField4.getText().length() == 0 || jPasswordField1.getText().length() == 0) {
                JOptionPane.showMessageDialog(null, "Please Fill up all the Fields!!");
            } else {
                System.out.println("begenning");
                Class.forName("oracle.jdbc.driver.OracleDriver");
                Connection conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521/xe", Login.orclusername, "Kirthic2002");//your username and password
                String sql = "update student set name ='"+jTextField1.getText()+"',rollno='"+jTextField2.getText()+"',department='"+jTextField3.getText()+"',section='"+jTextField4.getText()+"',username='"+jTextField2.getText()+"',password='"+jPasswordField1.getText()+"'where rollno='"+rno+"'" ;
                System.out.println(sql);
                PreparedStatement ps = conn.prepareStatement(sql);
                ResultSet rs = ps.executeQuery();

                if (rs.next()) {

                    System.out.println("admin update");
                    JOptionPane.showMessageDialog(null, "Student Added Successfully!!");
                    dispose();
                    AdminHome adminHome = new AdminHome();
                    adminHome.setVisible(true);
                    sql="update admin set username='"+jTextField2.getText()+"',password='"+jPasswordField1.getText()+"'where username='"+uname+"'";
                    ps = conn.prepareStatement(sql);
                    rs = ps.executeQuery();
                    System.out.println("admin entry");

                    System.out.println("hii");
                    try {
                        System.out.println("halo");
                        String sql1="select courseid from course";
                        PreparedStatement ps1 = conn.prepareStatement(sql1);
                        ResultSet rs1= ps1.executeQuery();

                        while(rs1.next())
                        {
                            System.out.println("attendance update");
                            String sql2 = "update attendance set rollno = '"+jTextField2.getText()+"' where rollno='"+rno+"' and courseid='"+rs1.getString("courseid")+"'";
                            System.out.println(sql2);
                            PreparedStatement ps2 = conn.prepareStatement(sql2);
                            ResultSet rs2 = ps2.executeQuery();
                        }


                    } catch (Exception e) {
                        System.out.println(e);
                    }
                }
            }
        }catch (Exception e)
        {
            System.out.println(e);
        }
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here BACK:
        dispose();
        StudentKey studentKey = new StudentKey();
        studentKey.setVisible(true);
    }



    // Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration
}