import javax.swing.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

public class Login extends javax.swing.JFrame {

    public static final String orclusername="final";
    public static String username;
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1090, 720));
        setMinimumSize(new java.awt.Dimension(1090, 720));
        setPreferredSize(new java.awt.Dimension(1090, 720));
        setSize(new java.awt.Dimension(1090, 720));

        jPanel1.setBackground(new java.awt.Color(235, 238, 239));
        jPanel1.setMaximumSize(new java.awt.Dimension(1090, 720));
        jPanel1.setMinimumSize(new java.awt.Dimension(1090, 720));
        jPanel1.setPreferredSize(new java.awt.Dimension(1090, 720));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setText("PSG COLLEGE OF TECHNOLOGY");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 200, 790, 56);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PSG LOGO.jpg"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(1010, 10, 65, 90);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel4.setText("USERNAME");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 400, 140, 25);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel5.setText("PASSWORD");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 465, 140, 25);

        jTextField1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel1.add(jTextField1);
        jTextField1.setBounds(210, 395, 230, 35);

        jPasswordField1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel1.add(jPasswordField1);
        jPasswordField1.setBounds(210, 460, 230, 35);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel6.setText("ATTENDANCE MANAGEMENT SYSTEM");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 300, 700, 30);

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton1.setText("LOGIN");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(460, 600, 110, 33);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BACKGROUND.jpg"))); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(1090, 720));
        jLabel2.setMinimumSize(new java.awt.Dimension(1090, 720));
        jLabel2.setPreferredSize(new java.awt.Dimension(1090, 720));
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 1090, 720);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, 0)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1090, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO LOGIN BUTTON:
        String password = jPasswordField1.getText();
        String username = jTextField1.getText();

        try
        {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection conn= DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521/xe",orclusername,"Kirthic2002");

            String sql="select * from admin where username='"+jTextField1.getText()+"' and password='"+jPasswordField1.getText()+"'";
            PreparedStatement ps=conn.prepareStatement(sql);
            ResultSet rs=ps.executeQuery();

            if(rs.next())
            {

                JOptionPane.showMessageDialog(null,"Login Sussessfull!!");

                if("1".compareTo(rs.getString("ID"))==0)
                {

                    AdminHome adminhome = new AdminHome();
                    adminhome.setVisible(true);
                }
                else if("2".compareTo(rs.getString("ID"))==0)
                {
                    TeacherHome teacherHome = new TeacherHome();
                    System.out.println(jTextField1.getText());
                    Login.username=jTextField1.getText();
                    teacherHome.setVisible(true);
                }
                else if("3".compareTo(rs.getString("ID"))==0)
                {
                    //for student
                    dispose();
                    StudentHome studentHome=new StudentHome();
                    studentHome.setVisible(true);
                    Login.username=jTextField1.getText();

                }
                setVisible(false);
            }
            else{
                System.out.println(rs.getString("username"));
                JOptionPane.showMessageDialog(null,"Invalid username or password!!!");
            }
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration
}